apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontendDeploymentName }}
  namespace: {{ .Values.frontendNamespaceName }}
  labels:
    app: {{ .Values.frontendImageName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.frontendImageName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontendImageName }}
    spec:
      containers:
        - name: {{ .Values.frontendImageName }}
          image: {{ .Values.frontendImage }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: {{ .Values.frontendRequests.memory | quote }}
              cpu: {{ .Values.frontendRequests.cpu | quote }}
            limits:
              memory: {{ .Values.frontendLimits.memory | quote }}
              cpu: {{ .Values.frontendLimits.cpu | quote }}
          ports:
            - containerPort: 80
